[phases.setup]
nixPkgs = ["nodejs_18", "python39", "python39Packages.pip", "gcc", "pkg-config"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm ci",
    "pip install --no-cache-dir --prefer-binary -r requirements_backend.txt",
    "playwright install --with-deps chromium"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build:web"]

[start]
cmd = "npm run start:prod"

[variables]
PIP_PREFER_BINARY = "1"
PIP_NO_CACHE_DIR = "1" 