[build]
builder = "nixpacks"
buildCommand = "npm ci && pip install --no-cache-dir --prefer-binary -r requirements_backend.txt && playwright install chromium && npm run build:web"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
PYTHONPATH = "/app"
PIP_PREFER_BINARY = "1" 